In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("EV_cars.csv")

In [3]:
df

,Battery,Car_name,Car_name_link,Efficiency,Fast_charge,Price.DE.,Range,Top_speed,acceleration..0.100.
0,75.0,Tesla Model Y Long Range Dual Motor,https://ev-database.org/car/1619/Tesla-Model-Y...,172,670.0,59017.0,435,217,5.0
1,57.5,Tesla Model 3,https://ev-database.org/car/1991/Tesla-Model-3,137,700.0,46220.0,420,201,6.1
2,60.5,BYD ATTO 3,https://ev-database.org/car/1782/BYD-ATTO-3,183,370.0,44625.0,330,160,7.3
3,61.7,MG MG4 Electric 64 kWh,https://ev-database.org/car/1708/MG-MG4-Electr...,171,630.0,39990.0,360,160,7.9
4,75.0,Tesla Model 3 Long Range Dual Motor,https://ev-database.org/car/1992/Tesla-Model-3...,149,780.0,55220.0,505,201,4.4
...,...,...,...,...,...,...,...,...,...
355,46.3,Citroen e-Jumpy Combi XL 50 kWh,https://ev-database.org/car/1596/Citroen-e-Jum...,257,290.0,52730.0,180,130,12.1
356,46.3,Fiat E-Ulysse L2 50 kWh,https://ev-database.org/car/1721/Fiat-E-Ulysse...,250,290.0,55990.0,185,130,12.1
357,46.3,Opel Vivaro-e Combi L 50 kWh,https://ev-database.org/car/1601/Opel-Vivaro-e...,257,290.0,51825.0,180,130,12.1
358,68.0,Opel Zafira-e Life M 75 kWh,https://ev-database.org/car/1348/Opel-Zafira-e...,257,290.0,69250.0,265,130,13.3
359,46.3,Fiat E-Ulysse L3 50 kWh,https://ev-database.org/car/1723/Fiat-E-Ulysse...,257,290.0,56990.0,180,130,12.1

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Battery               360 non-null    float64
 1   Car_name              360 non-null    object
 2   Car_name_link         360 non-null    object
 3   Efficiency            360 non-null    int64
 4   Fast_charge           358 non-null    float64
 5   Price.DE.             309 non-null    float64
 6   Range                 360 non-null    int64
 7   Top_speed             360 non-null    int64
 8   acceleration..0.100.  360 non-null    float64
dtypes: float64(4), int64(3), object(2)
memory usage: 25.4+ KB
None

In [5]:
# 1.Load Data

df = pd.read_csv('EV_cars.csv') # Replace with your actual CSV file path
print("Original Data Shape:", df.shape)
print(df.head())

Original Data Shape: (360, 9)
   Battery                             Car_name  \
0     75.0  Tesla Model Y Long Range Dual Motor
1     57.5                        Tesla Model 3
2     60.5                           BYD ATTO 3
3     61.7               MG MG4 Electric 64 kWh
4     75.0  Tesla Model 3 Long Range Dual Motor

                                       Car_name_link  Efficiency  Fast_charge  \
0  https://ev-database.org/car/1619/Tesla-Model-Y...         172        670.0
1     https://ev-database.org/car/1991/Tesla-Model-3         137        700.0
2        https://ev-database.org/car/1782/BYD-ATTO-3         183        370.0
3  https://ev-database.org/car/1708/MG-MG4-Electr...         171        630.0
4  https://ev-database.org/car/1992/Tesla-Model-3...         149        780.0

   Price.DE.  Range  Top_speed  acceleration..0.100.
0    59017.0    435        217                   5.0
1    46220.0    420        201                   6.1
2    44625.0    330        160                   7.3
3    39990.0    360        160                   7.9
4    55220.0    505        201                   4.4

In [6]:
# 2.Basic Info

print("\nData Types:\n", df.dtypes)
print("\nMissing Values:\n", df.isnull().sum())

Data Types:
 Battery                 float64
Car_name                 object
Car_name_link            object
Efficiency                int64
Fast_charge             float64
Price.DE.               float64
Range                     int64
Top_speed                 int64
acceleration..0.100.    float64
dtype: object

Missing Values:
 Battery                  0
Car_name                 0
Car_name_link            0
Efficiency               0
Fast_charge              2
Price.DE.               51
Range                    0
Top_speed                0
acceleration..0.100.     0
dtype: int64

In [7]:
# 3.Handle Missing Values

# Separate numerical and categorical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

# Numerical: Replace with mean
num_imputer = SimpleImputer(strategy='mean')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

# Categorical: Replace with mode
if len(cat_cols) > 0:
    cat_imputer = SimpleImputer(strategy='most_frequent')
    df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [8]:
# 4.Encode Categorical Variables
ohe_cols = ['Car_name', 'Car_name_link']
df = pd.get_dummies(df, columns=ohe_cols, drop_first=True)
print("Encoding completed successfully!")
print(df.head())

Encoding completed successfully!
   Battery  Efficiency  Fast_charge  Price.DE.  Range  Top_speed  \
0     75.0       172.0        670.0    59017.0  435.0      217.0
1     57.5       137.0        700.0    46220.0  420.0      201.0
2     60.5       183.0        370.0    44625.0  330.0      160.0
3     61.7       171.0        630.0    39990.0  360.0      160.0
4     75.0       149.0        780.0    55220.0  505.0      201.0

   acceleration..0.100.  Car_name_Abarth 500e Hatchback  Car_name_Aiways U5  \
0                   5.0                           False               False
1                   6.1                           False               False
2                   7.3                           False               False
3                   7.9                           False               False
4                   4.4                           False               False

   Car_name_Aiways U6  ...  \
0               False  ...
1               False  ...
2               False  ...
3               False  ...
4               False  ...

   Car_name_link_https://ev-database.org/car/2038/Ford-Mustang-Mach-E-GT  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2039/Citroen-e-C3  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2040/BMW-iX2-xDrive30  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2041/Smart-1-Pro  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2042/Nissan-Townstar-EV-Passenger  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2044/Hyundai-IONIQ-5-N  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2045/Mercedes-EQE-SUV-300  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2046/Mercedes-EQE-SUV-350plus  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2047/Mercedes-EQE-SUV-350-4MATIC  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Car_name_link_https://ev-database.org/car/2048/Mercedes-EQE-SUV-500-4MATIC
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

[5 rows x 716 columns]

In [11]:
# 5.Outlier Detection and Treatment (using IQR)

for col in num_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  df[col] = np.where(df[col] < lower, lower, df[col])
  df[col] = np.where(df[col] > upper, upper, df[col])

In [12]:
# 6.Feature Scaling

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [13]:
from sklearn.feature_selection import SelectKBest, f_regression
target_col = 'Price.DE.'  # Replace with your actual target column name

if target_col in df.columns:
    X = df.drop(target_col, axis=1)
    y = df[target_col]

    bestfeatures = SelectKBest(score_func=f_regression, k=10)
    fit = bestfeatures.fit(X, y)

    selected_features = X.columns[fit.get_support()]
    df = df[selected_features.to_list() + [target_col]]

    print("\nSelected Features:", selected_features.to_list())

corr = df.corr()
corr.sort_values(by='Price.DE.', ascending=False)

Selected Features: ['Battery', 'Efficiency', 'Fast_charge', 'Range', 'Top_speed', 'acceleration..0.100.', 'Car_name_link_https://ev-database.org/car/2009/Mercedes-EQS-450-4MATIC', 'Car_name_link_https://ev-database.org/car/2010/Mercedes-EQS-500-4MATIC', 'Car_name_link_https://ev-database.org/car/2011/Mercedes-EQS-580-4MATIC', 'Car_name_link_https://ev-database.org/car/2012/Mercedes-EQS-AMG-53-4MATICplus']

,Battery,Efficiency,Fast_charge,Range,Top_speed,acceleration..0.100.,Car_name_link_https://ev-database.org/car/2009/Mercedes-EQS-450-4MATIC,Car_name_link_https://ev-database.org/car/2010/Mercedes-EQS-500-4MATIC,Car_name_link_https://ev-database.org/car/2011/Mercedes-EQS-580-4MATIC,Car_name_link_https://ev-database.org/car/2012/Mercedes-EQS-AMG-53-4MATICplus,Price.DE.
Price.DE.,0.753339,0.255468,0.589014,0.611306,0.715349,-0.528232,0.101915,0.101915,0.101915,0.101915,1.000000
Battery,1.000000,0.181698,0.591218,0.882014,0.705304,-0.609218,0.096457,0.096457,0.096457,0.096457,0.753339
Top_speed,0.705304,-0.175993,0.780110,0.751078,1.000000,-0.849573,0.043531,0.043531,0.043531,0.102952,0.715349
Range,0.882014,-0.277273,0.713594,1.000000,0.751078,-0.746813,0.118469,0.108610,0.108610,0.081499,0.611306
Fast_charge,0.591218,-0.271726,1.000000,0.713594,0.780110,-0.672166,0.080478,0.073725,0.073725,0.055718,0.589014
Efficiency,0.181698,1.000000,-0.271726,-0.277273,-0.175993,0.389138,-0.028860,-0.018436,-0.018436,0.014575,0.255468
Car_name_link_https://ev-database.org/car/2010/Mercedes-EQS-500-4MATIC,0.096457,-0.018436,0.073725,0.108610,0.043531,-0.044100,-0.002786,1.000000,-0.002786,-0.002786,0.101915
Car_name_link_https://ev-database.org/car/2012/Mercedes-EQS-AMG-53-4MATICplus,0.096457,0.014575,0.055718,0.081499,0.102952,-0.069016,-0.002786,-0.002786,-0.002786,1.000000,0.101915
Car_name_link_https://ev-database.org/car/2009/Mercedes-EQS-450-4MATIC,0.096457,-0.028860,0.080478,0.118469,0.043531,-0.029862,1.000000,-0.002786,-0.002786,-0.002786,0.101915
Car_name_link_https://ev-database.org/car/2011/Mercedes-EQS-580-4MATIC,0.096457,-0.018436,0.073725,0.108610,0.043531,-0.052998,-0.002786,-0.002786,1.000000,-0.002786,0.101915
acceleration..0.100.,-0.609218,0.389138,-0.672166,-0.746813,-0.849573,1.000000,-0.029862,-0.044100,-0.052998,-0.069016,-0.528232

In [14]:
import numpy as np
import sklearn.preprocessing as preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Price.DE.'])
y = np.asarray(df['Price.DE.'])

# Scale the features using preprocessing.StandardScaler()
X = preprocessing.StandardScaler().fit(X).transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size = 0.3, random_state = 100)

print ('Train set:', X_train.shape, y_train.shape)
print ('Test set:', X_test.shape, y_test.shape)

Train set: (252, 10) (252,)
Test set: (108, 10) (108,)

In [15]:
#Regression Models
#1.Linear Regression

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.6978390991974269

In [16]:
#2.Decision Tree

from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.6183287291664914

In [17]:
#3.Random Forest
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.7700101447369083

In [18]:
#4.K-Nearest Neighbors

from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.7668311627876698

In [19]:
#5.Support Vector Regression

from sklearn.svm import SVR
model = SVR()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.7476631308143549

In [20]:
#6.Gradient Boosting

from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.7766564905949208

In [21]:
#7.Ridge Regression

from sklearn.linear_model import Ridge
model = Ridge(alpha=1.0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.6975661256888852